# Generated by Django 6.0.6 on 2026-06-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_question_certificate_choice_quiz_question_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo video URL', null=True),
        ),
    ]
