# Generated by Django 6.0.6 on 2026-06-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
