services:
  - type: web
    name: theta-tutorial-center
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn theta_backend.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: theta_backend.settings
      - key: DEBUG
        value: false
    plan: free

databases:
  - name: theta-db
    plan: free
    databaseName: theta_db
    user: theta_user